# Generated by Django 5.2.8 on 2026-01-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='target_fps',
            field=models.FloatField(default=24.0),
        ),
        migrations.AddField(
            model_name='project',
            name='target_height',
            field=models.PositiveIntegerField(default=1080),
        ),
        migrations.AddField(
            model_name='project',
            name='target_width',
            field=models.PositiveIntegerField(default=1920),
        ),
    ]
