# Generated by Django 5.2.8 on 2025-12-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='video_timecode',
            field=models.CharField(blank=True, help_text='Ej: 00:01:45:12', max_length=12),
        ),
    ]
