# Generated by Django 5.2.8 on 2026-01-18 02:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_comment_video_timecode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['-version_number']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='video_timecode',
        ),
        migrations.AddField(
            model_name='comment',
            name='timecode',
            field=models.CharField(blank=True, help_text='Código de tiempo (HH:MM:SS:FF)', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='version',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='license',
            name='provider',
            field=models.CharField(help_text='Titular de Derechos (ej. Warner, Sony)', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='matricula',
            field=models.CharField(help_text='Identificador único institucional', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image_path',
            field=models.CharField(blank=True, help_text='Ruta S3 al poster/miniatura', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='synopsis',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='version',
            name='approval_status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='version',
            name='original_file_path',
            field=models.CharField(help_text='Ruta al Master inmutable en S3', max_length=500),
        ),
        migrations.AlterField(
            model_name='version',
            name='proxy_file_path',
            field=models.CharField(blank=True, help_text='Ruta al proxy H.264 procesado', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='transcoding_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('ERROR', 'Error')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='version',
            name='uploaded_by',
            field=models.ForeignKey(help_text='Auditoría de quién subió el archivo', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.IntegerField(help_text='Iteración del corte (1, 2, 3...)'),
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('project', 'version_number')},
        ),
    ]
