# Generated by Django 5.2.8 on 2026-01-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_project_target_fps_project_target_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
