# Generated by Django 5.2.8 on 2026-02-02 17:33

import pipeline.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_version_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='color_space',
            field=models.CharField(default='ACEScg', max_length=500),
        ),
        migrations.AlterField(
            model_name='version',
            name='file',
            field=models.FileField(max_length=1000, upload_to=pipeline.utils.asset_version_path, verbose_name='Original File'),
        ),
        migrations.AlterField(
            model_name='version',
            name='proxy_file_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
