# Generated by Django 5.2.8 on 2026-01-20 16:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_alter_version_options_remove_comment_video_timecode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='timecode',
        ),
        migrations.RemoveField(
            model_name='license',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='license',
            name='project',
        ),
        migrations.RemoveField(
            model_name='license',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='license',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cover_image_path',
        ),
        migrations.RemoveField(
            model_name='project',
            name='synopsis',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='license',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='license',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='Student', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.license'),
        ),
        migrations.AddField(
            model_name='version',
            name='parent_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='pipeline.version'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='version',
            name='approval_status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DEPRECATED', 'Deprecated')], default='PENDING_REVIEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='version',
            name='original_file_path',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='version',
            name='proxy_file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.IntegerField(),
        ),
    ]
