# Generated by Django 5.2.8 on 2026-01-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_rename_text_comment_body_remove_comment_timecode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(default='Artist', max_length=50),
        ),
    ]
