# Generated by Django 5.2.8 on 2026-02-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_alter_version_color_space_alter_version_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='thumbnails/'),
        ),
    ]
