# Generated by Django 5.2.8 on 2026-02-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0005_alter_version_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='duration',
            field=models.FloatField(blank=True, null=True, verbose_name='Duration (sec)'),
        ),
        migrations.AddField(
            model_name='version',
            name='filesize',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='File Size (bytes)'),
        ),
    ]
