# Generated by Django 5.2.8 on 2026-02-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0006_version_duration_version_filesize'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_score', models.FloatField(default=100.0)),
                ('database_score', models.FloatField(default=100.0)),
                ('ffmpeg_score', models.FloatField(default=100.0)),
                ('integrity_score', models.FloatField(default=100.0)),
                ('last_diagnostic', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Health',
                'verbose_name_plural': 'System Health',
            },
        ),
    ]
