# Generated by Django 5.2.8 on 2026-02-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0007_systemhealth'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('VIDEO', 'Video/Footage'), ('3D', '3D Model/Asset'), ('AUDIO', 'Audio/Score'), ('CODE', 'Script/Tool'), ('IMAGE', 'Texture/Concept'), ('OTHER', 'Generic Data')], default='VIDEO', max_length=10),
        ),
        migrations.AddField(
            model_name='version',
            name='extra_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
