# Generated by Django 5.2.8 on 2026-02-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0008_asset_category_version_extra_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
