# Generated by Django 5.2.8 on 2026-02-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0009_alter_version_version_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='color_space',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='proxy_file_path',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='version',
            name='timecode_start',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
