# Generated by Django 5.2.8 on 2026-02-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0010_alter_version_color_space_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='department',
            field=models.CharField(choices=[('ED', 'Editorial'), ('LAY', 'Layout'), ('ANIM', 'Animation'), ('FX', 'Effects'), ('LGT', 'Lighting'), ('COMP', 'Compositing'), ('ART', 'Art/Concept'), ('GEN', 'Generic/Asset')], default='GEN', max_length=4, verbose_name='Department'),
        ),
    ]
