# Generated by Django 5.2.8 on 2026-03-18 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0011_version_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AddField(
            model_name='comment',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Critical')], default=2),
        ),
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[('TECH', 'Technical Note'), ('ART', 'Artistic Note'), ('PIPE', 'Pipeline/Tool Error'), ('GEN', 'General')], default='GEN', max_length=4),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='version',
            name='review_notes',
            field=models.TextField(blank=True, help_text='Notas técnicas o artísticas del supervisor.', null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora exacta de la decisión.', null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última revisión.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='Comment Body'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='frame_number',
            field=models.PositiveIntegerField(blank=True, help_text='Fotograma específico al que se refiere la nota.', null=True, verbose_name='Frame'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_resolved',
            field=models.BooleanField(default=False, help_text='Indica si el artista ya atendió esta nota.'),
        ),
        migrations.AlterField(
            model_name='version',
            name='approval_status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CBB', 'CBB (Change Requested)'), ('DEPRECATED', 'Deprecated')], default='PENDING_REVIEW', max_length=20),
        ),
    ]
