# Generated by Django 5.2.8 on 2026-03-18 07:00

import pipeline.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0012_alter_comment_options_comment_priority_comment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='license',
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('asset', 'version_number', 'department')},
        ),
        migrations.AlterField(
            model_name='version',
            name='file',
            field=models.FileField(max_length=1000, upload_to=pipeline.models.get_version_path, verbose_name='Original File'),
        ),
        migrations.DeleteModel(
            name='License',
        ),
    ]
