# Generated by Django 5.2.8 on 2026-04-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0013_remove_project_license_alter_version_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='checksum_sha256',
            field=models.CharField(blank=True, db_index=True, help_text='ADN único de esta entrega específica.', max_length=64, null=True),
        ),
    ]
